# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20150430_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='ideas',
            field=models.ManyToManyField(blank=True, to='blog.Idea'),
        ),
        migrations.AlterField(
            model_name='note',
            name='thoughts',
            field=models.ManyToManyField(blank=True, to='blog.Thought'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
