# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20181107_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
