# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_highlight_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglistitem',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
