# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20190106_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.IntegerField(choices=[(0, 'Create Idea'), (1, 'Edited Idea'), (2, 'Deleted Idea'), (3, 'Started Draft'), (4, 'Published Draft'), (5, 'Edited Draft'), (6, 'Moved Draft'), (7, 'Trashed Draft'), (8, 'Untrashed Draft'), (9, 'Deleted Draft'), (10, 'Published Thought'), (11, 'Unpublished Thought'), (12, 'Edited Thought'), (13, 'Moved Thought'), (14, 'Trashed Thought'), (15, 'Untrashed Thought'), (16, 'Deleted Thought'), (17, 'Added New Highlight'), (18, 'Edited Highlight'), (19, 'Deleted Highlight'), (20, 'Added Book to Recently Read List'), (21, 'Added Book to Wish List'), (22, 'Edited Book'), (23, 'Moved Book to Recently Read List'), (24, 'Deleted Book'), (25, 'Added New Task Item'), (26, 'Edited Task Item'), (27, 'Deleted Task Item'), (28, 'Marked Task Item as Completed'), (29, 'Changed Task Priority'), (30, 'Started New Note'), (31, 'Edited Note'), (32, 'Deleted Note'), (33, 'Tweet')]),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='icon',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Next')], default=1),
        ),
        migrations.AlterField(
            model_name='thought',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
